# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="vasatanasov/ubuntu-dob"
    web.vm.hostname = "web.dob.lab"
    web.vm.network "private_network", ip: "192.168.89.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.provider "virtualbox" do |vb|
      vb.name = "WEB"
    end
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box="vasatanasov/ubuntu-dob"
    db.vm.hostname = "db.dob.lab"
    db.vm.network "private_network", ip: "192.168.89.101"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "DB"
    end
    db.vm.provision "shell", path: "db.sh"
  end

end