CREATE TABLE IF NOT EXISTS MAKER
(
    ID      VARCHAR(12)  NOT NULL PRIMARY KEY,
    NAME    VARCHAR(255) NOT NULL UNIQUE,
    POPULAR BIT(1)
);

CREATE TABLE IF NOT EXISTS MODEL
(
    ID       VARCHAR(12)  NOT NULL PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL,
    POPULAR  BIT(1),
    MAKER_ID VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS CAR
(
    ID       VARCHAR(12) NOT NULL PRIMARY KEY,
    YEAR     INT         NOT NULL,
    MODEL_ID VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS `TRIM`
(
    ID     VARCHAR(12)  NOT NULL PRIMARY KEY,
    NAME   VARCHAR(255) NOT NULL,
    CAR_ID VARCHAR(12)
);

ALTER TABLE MODEL
    ADD CONSTRAINT FK_MODEL_MAKE_ID FOREIGN KEY (MAKER_ID) REFERENCES MAKER (ID);

ALTER TABLE CAR
    ADD CONSTRAINT FK_CAR_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES MODEL (ID);

ALTER TABLE TRIM
    ADD CONSTRAINT FK_TRIM_CAR_ID FOREIGN KEY (CAR_ID) REFERENCES CAR (ID);
