version: "3.9"

services:
    client:
        image: 127.0.0.1:5000/client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3001:80"
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        deploy:
            mode: replicated
            replicas: 3
        networks:
            - frontend

    api:
        image: 127.0.0.1:5000/api
        build:
            context: ./api
            dockerfile: Dockerfile
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        environment: 
            - DB_URL=${DB_URL}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test: "${DOCKER_API_HEALTHCHECK_TEST:-curl localhost:8007/up}"
            interval: "20s"
            timeout: "15s"
            start_period: "15s"
            retries: 3
        ports:
            - "8007:8007"
        networks:
            - frontend
            - backend

    db:
        image: mariadb:10.6
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        volumes:
            - mysql:/var/lib/mysql
            - ./db/scripts:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - backend

volumes:
    mysql:

networks:
    backend:
    frontend:
