version: "3.9"

services:
    web:
        image: shekeriev/dob-w3-php
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/shared/app/php:/var/www/html:ro"
        networks:
            - swrm-network
        depends_on:
            - db

    db:
        image: shekeriev/dob-w3-mysql
        networks:
            - swrm-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"

networks:
    swrm-network:
