#!/usr/bin/env ansible-playbook
---
- hosts: webservers
  become: true
  tasks:
    - debug:
            msg: "{{ playbook_dir }}"
    - name: Up pod
      command: "docker-compose -f /home/vagrant/shared/web/docker-compose.yml up --build -d"
      become: yes