#!/usr/bin/env ansible-playbook
---
- hosts: dbservers
  become: true
  vars:
      docker_volume: db_data
      docker_network: web_net
      db_name: bulgaria
  tasks:
      - name: "Create a Volume"
        docker_volume:
            name: "{{ docker_volume }}"

      - name: "Build docker image"
        command: docker build -t db:latests /home/vagrant/shared/db 
        become: yes

      - name: "Launch database container"
        docker_container:
            name: "{{ db_name }}"
            image: db:latests
            volumes:
                - "{{ docker_volume }}:/var/lib/mysql:rw"
                - /home/vagrant/shared/db/scripts:/docker-entrypoint-initdb.d
            restart_policy: always
            env:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: bulgaria
                MYSQL_USER: web_user
                MYSQL_PASSWORD: Password1
            ports:
                - "3306:3306"
