---
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create default containers
  docker_container:
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    state: started
    ports: '{{ nginx_published_ports }}'
    exposed_ports: '{{ nginx_exposed_ports }}'