VAGRANTFILE_API_VERSION: "2"

###################
# VMs (vagrant) settings
###################

default: &DEFAULT
    box: "ubuntu/focal64"
    # box: "vasatanasov/ubuntu-2004-server"
    # box:  "shekeriev/ubuntu-20-04-server"
    # box:  "ubuntu-2004-ubuntu"
    cpu: 1
    memory: 1024
    vram: 128
    synced_folder: "/home/vagrant/shared"

machines:
    ans:
        <<: *DEFAULT
        # box: "ubuntu-2004-ansible"
        hostname: "ans.dob.lab"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.99
                netmask: 192.168.98.0/24
    web:
        <<: *DEFAULT
        # box: "shekeriev/ubuntu-20-04-server"
        hostname: "web.dob.lab"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.100
                netmask: 192.168.98.0/24
        forwarded_port:
            - guest: 80
              host: 8080
    db:
        <<: *DEFAULT
        hostname: "db.dob.lab"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.101
                netmask: 192.168.98.0/24
    clnt:
        <<: *DEFAULT
        hostname: "clnt.dob.lab"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.102
                netmask: 192.168.98.0/24
