VAGRANTFILE_API_VERSION: "2"

###################
# VMs (vagrant) settings
###################

default: &DEFAULT
    box: "vasatanasov/ubuntu-2004-ansible"
    cpu: 1
    memory: 1024
    vram: 16
    synced_folder: "/home/vagrant/shared"

machines:
    ans:
        <<: *DEFAULT
        # box: "ubuntu-2004-ansible"
        hostname: "dob-ans"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.99
                netmask: 192.168.98.0/24
    web:
        <<: *DEFAULT
        # box: "shekeriev/ubuntu-20-04-server"
        hostname: "dob-web"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.100
                netmask: 192.168.98.0/24
        forwarded_port:
            - guest: 80
              host: 8080
    db:
        <<: *DEFAULT
        hostname: "dob-db"
        network:
            # Private/Host-only network
            private:
                address: 192.168.98.101
                netmask: 192.168.98.0/24