VAGRANTFILE_API_VERSION: "2"

###################
# VMs (vagrant) settings
###################

default: &DEFAULT
    box: "vasatanasov/ubuntu-2004-ansible"
    cpu: 1
    memory: 2048
    vram: 16
    synced_folder: "/home/vagrant/shared"

machines:
    web:
        <<: *DEFAULT
        box: "shekeriev/centos-8-minimal"
        hostname: "dob-web"
        network:
            # Private/Host-only network
            private:
                address: 192.168.11.155
        forwarded_port:
            - guest: 80
              host: 8080
              auto_correct: true
              id: "app"
    db:
        <<: *DEFAULT
        hostname: "dob-db"
        network:
            # Private/Host-only network
            private:
                address: 192.168.11.157
        forwarded_port:
            - guest: 3306
              host: 3307
              auto_correct: true
              id: "db"
    ans:
        <<: *DEFAULT
        hostname: "dob-ans"
        network:
            # Private/Host-only network
            private:
                address: 192.168.11.153
    # db2:
    #     <<: *DEFAULT
    #     box: "shekeriev/centos-8-minimal"
    #     hostname: "dob2-db"
    #     network:
    #         # Private/Host-only network
    #         private:
    #             address: 192.168.11.159
